### ISSUE TITLE
Error: Cannot find module 'web-component-tester-istanbul'

### ISSUE THREAD

**Issue by csbrandt** [thedeeno/web-component-tester-istanbul#2]
web-component-tester-istanbul is in node_modules after running ```npm install web-component-tester-istanbul --saveDev```

wct.conf.js

```
module.exports = {
    verbose: true,
    plugins: {
        "web-component-tester-istanbul": {

            dir: "./coverage",

            reporters: ["text-summary", "lcov"],

            include: [
                "scripts/*.js"
            ]

        }
    }
};
```

after running ```wct test/runner.html``` receive following error

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'web-component-tester-istanbul'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/lib/node_modules/web-component-tester/runner/config.js:185:26
    at Function.forOwn (/usr/lib/node_modules/web-component-tester/node_modules/lodash/dist/lodash.js:2105:15)
    at lodash.ctor.(anonymous function) [as forOwn] (/usr/lib/node_modules/web-component-tester/node_modules/lodash/dist/lodash.js:5924:31)
    at mergePlugins (/usr/lib/node_modules/web-component-tester/runner/config.js:184:22)
    at Object.fromEnv (/usr/lib/node_modules/web-component-tester/runner/config.js:146:13)
    at Object.run (/usr/lib/node_modules/web-component-tester/runner/cli.js:26:24)
```

**Comment by thedeeno** [comment]
Hmm, I'll see if I can reproduce and get back to you tomorrow. The plugin looks like it's configure correctly. What version of WCT are you using?

**Comment by toadkicker** [comment]
Hey I just wanted to drop some notes here too trying to get this working:

* You have to put the plugin section in wct.conf.json; adding it to grunt/gulp is wrong.
* I had to install istanbul manually using --global (-g) despite it being in package.json here.
* The example covers js files only, so if html files have scripts in them you have to add `*.html`'s to the configuration.

**Comment by nevir** [comment]
@thedeeno That's from the (now yanked) WCT 2.1.* line - I completely reworked plugins (and subsequently broke this one)

I'm going to see about submitting a patch to convert this over

**Comment by nevir** [comment]
WCT's got a new plugin system coming down the pipe that should ease this; it'll be a bit of work to convert this plugin over to the new format, but hopefully simplifies the plugin loading process

**Comment by Klathmon** [comment]
I've already started on a fork slowly porting it to the new system. I'm gonna push some of those changes later today if i have time.

**Comment by nevir** [comment]
Awesome! Also, in case you haven't seen it, I've got a (completely undocumented) [hook for the web server](https://github.com/Polymer/web-component-tester/blob/master/runner/webserver.js#L105) that exposes the express object out:

So in the plugin it's:

```js
module.exports = function(wct) {
  wct.hook('prepare:webserver', function(express, done) {
    // ...
  });
};
```

**Comment by Klathmon** [comment]
That's actually exactly where i stopped, so that'll help, thanks!
