### ISSUE TITLE
 Coverage summary always 0/0 for all stats

### ISSUE THREAD

**Issue by nguyenhuedang** [thedeeno/web-component-tester-istanbul#34]
I set up WCT and WCT-Istanbul for testing my Polymer project.
Here is my `wct.conf.js`:

	module.exports = {
		plugins: {
			'local': {
				browsers: ['chrome', 'firefox']
			},
			'istanbul': {
				dir: 'logs/coverage',
				reporters: ['text-summary', 'lcov'],
				include: [
					'*.html'
				],
				exclude: [

				]
			}
		}
	}

And what I got when the `wct` finishs:

	$ wct
	Received undefined
	Installing and starting Selenium server for local browsers
	Selenium server running on port 64746
	Web server running on port 2000 and serving from /Users/admin/tiki/Tiki-mobile-web
	(node:15734) DeprecationWarning: 'root' is deprecated, use 'global'
	firefox 47               Beginning tests via http://localhost:2000/components/Tiki-mobile-web/generated-index.html?cli_browser_id=1
	chrome 51                Beginning tests via http://localhost:2000/components/Tiki-mobile-web/generated-index.html?cli_browser_id=0
	firefox 47               Tests passed
	chrome 51                Tests passed
	Test run ended with great success

	=============================== Coverage summary ===============================
	Statements   : 100% ( 0/0 )
	Branches     : 100% ( 0/0 )
	Functions    : 100% ( 0/0 )
	Lines        : 100% ( 0/0 )
	================================================================================

My current version of web-component-tester-istanbul is 0.10.1, which install by

`npm install --save-dev https://github.com/t2ym/web-component-tester-istanbul/tarball/0.10.1`

My current version of web-component-tester is 4.3.1.

Any help?

**Comment by eugef** [comment]
@nguyenhuedang try change `'*.html'` to `'**/*.html'`

**Comment by nguyenhuedang** [comment]
@eugef It's worked, thanks so much!
