### ISSUE TITLE
TypeError: express.use is not a function

### ISSUE THREAD

**Issue by lukasoppermann** [thedeeno/web-component-tester-istanbul#37]
When I try to run the test I always get this error `TypeError: express.use is not a function`.

It does not matter if I run wct from within `node_modules` or the global installation. When I remove the plugin again it works fine and all tests pass.

My `wct.conf.js` has this content:

``` js
module.exports = {
    "verbose": false,
    "plugins": {
        "local": {
          "browsers": ["chrome"]
      },
      istanbul: {
        dir: "./coverage",
        reporters: ["text-summary", "lcov"],
        include: [
          "src/*.js"
        ],
        exclude: [
          "/polymer/polymer.js",
          "/platform/platform.js"
        ]
      }
    }
};
```

**Comment by banksean** [comment]
I get this too.

Based on some debug statements I inserted, I think the first parameter (named "express") in [plugin.js line 40](https://github.com/thedeeno/web-component-tester-istanbul/blob/master/lib/plugin.js#L40) is actually the done() function, rather than the express app instance it's expecting.

I'm using wct 4.3.5.

**Comment by banksean** [comment]
Related: The WCT has a [bug in how it calls emitHook](https://github.com/Polymer/web-component-tester/issues/373) for 'prepare:webserver'. [Here's a PR](https://github.com/Polymer/web-component-tester/pull/399) that fixes it.

**Comment by lukasoppermann** [comment]
@banksean thanks, this does indeed fix it, hope they merge it soon, as it will otherwise not let me use it on travis.

**Comment by eugef** [comment]
This bug still happens for the WCT v5.0.0

**Comment by hyyan** [comment]
Any news about this issue ?

**Comment by alvaropinot** [comment]
you can try installing last WCT preview version as it was fixed at https://github.com/Polymer/web-component-tester/pull/445

if you are using a local `package.json` file

```
npm i -D web-component-tester@6.0.0-prerelease.2
```
or if you are using WCT globally 

```
npm i -g web-component-tester@6.0.0-prerelease.2
```

**Comment by eoutterson** [comment]
Any news?  This issue for me.

**Comment by akshay-kale** [comment]
try with web-component-tester@4.2.2
working for me
